### PR TITLE
Issue216 - fixing Wrapper CLAP host names

### PR DESCRIPTION
**Pull request by u-he-frank**

### CODE REVIEW

**Comment by baconpaul** [comment]
Heya! If you have clang-format installed you can run it across the code to fix CI. If you don't I can also do this and push to your branch. Just let me know which you prefer.
The change looks good to me and is a definite improvement!

**Comment by baconpaul** [comment]
Actually I pushed the clang format up just now since i was in the project anyway. lets see if CI passes.

@defiantnerd this looks god to me. Agree?

**Comment by defiantnerd** [comment]
Yes, I just would prefer to remove the prefix i from the symbol name. Apart of that, this looks very fine.

**Comment by defiantnerd** [comment]
fixes https://github.com/free-audio/clap-wrapper/issues/216, thanks @u-he-frank

**Pull request merged**
