### PR TITLE
Don't set MSVC to static runtime.

### PR DESCRIPTION
**Pull request by mtytel**
https://github.com/free-audio/clap-wrapper/issues/267

### CODE REVIEW

**Comment by baconpaul** [comment]
So in this case, I think we should set it if it is not otherwise set don't you?

That is, if it is set to nothing set it to static. 

I agree overriding the plugin author is aggravating but people use this as a top level cmake also. Can we if-test it ahead of time?

**Comment by mtytel** [comment]
If you include other cmake directories before clap-wrapper I think you'll get a conflict then and force the plugin dev to set it to DLL or static lib in their project anyway. 
Maybe if this was a full plugin framework it should set it but as a library that's probably included with other libraries I feel like it should just take the default.

**Comment by baconpaul** [comment]
Right. So the problem is we have two use cases

Users like you and me use it as a subordinate library to our project
Users like u-he use it as a standalone to build a wrapper configured to dynaload their remote clap

That's why leaving it unset seems like a tough path for users in the second case. See what I mean?

The top level cmake here does do stuff with command lines basically.

Lemme google a bit and ponder.

**Comment by baconpaul** [comment]
I dealt with this conditionally in [48861ec](https://github.com/free-audio/clap-wrapper/commit/48861ecf472fe2cbcd67478e3f5f0dabe9e5785c) so am going to close this PR.

**Pull request closed without merging**
