### PR TITLE
Version 0.10.0

### PR DESCRIPTION
**Pull request by defiantnerd**
Having ARA complete for VST3, I'd like to name this a 0.10.0 release.

### CODE REVIEW

**Comment by baconpaul** [comment]
I tagged main as 0.10.0 last week after we chatted in discord - the tag and changelog are all there and up to date. Did I miss a commit? We can make a 0.10.1 if so

**Comment by baconpaul** [comment]
Ahh yeah I tagged it but forgot to update the cmake :(

**Comment by baconpaul** [comment]
So I think what we should do is

Make this 0.10.1
Merge it
Then tag it 

since I would like tags to be immutable 

agree?

**Comment by defiantnerd** [comment]
I agree.

**Comment by baconpaul** [comment]
Ok I can handle that tonight or tomorrow morning

**Comment by baconpaul** [comment]
OK 0.10.1 is now main with this change, next and main are the same, the tag is there, CMakeLists has the right version, the changeling is updated, and we also included the two changes @mtytel made (VST3 timer and MSVC Runtime optional).

**Pull request merged**
