### PR TITLE
Add an small example and test of clap-first in-linked wrapper

### PR DESCRIPTION
**Pull request by baconpaul**
- Bring over my c99 distortion and make it C++
- Show that making all flavors as statically linked
- add it to CI

### CODE REVIEW

**Comment by baconpaul** [comment]
@defiantnerd this is me looking at the compile flags which tripped up matt and at the same time adding a simple 'clap first' test and example with static linking into the compionents. It's a draft because I want to add some doc and also make CI work. I'll tag you when its ready for review.

**Comment by baconpaul** [comment]
Link to #119 also

**Comment by baconpaul** [comment]
This also shows #257 and #258

**Comment by baconpaul** [comment]
OK @defiantnerd this is now ready for review

Basically what I did was add a small clap and show it linking statically into each of the wrappers, fixed the wrapper over-exports error problem, added some doc, added it to CI

Doing so showed up two errors in the wrapper which i didn't fix in this commit, but will happily pluck at this week.

Let me know what you think! I'm happy to merge this to next if you are.

**Comment by defiantnerd** [comment]
The stepped-bug is not a bug. My guess is that there is a bug in bitwig, but we have to check.

**Review by defiantnerd — APPROVED** [review]
Ok by me, so far I get it. I would merge it and we have a final checkup before merging to main.

**Pull request merged**
