### PR TITLE
fixed segfault on close, request timer on macOS standalone

### PR DESCRIPTION
**Pull request by MeijisIrlnd**
[followed on from this PR](https://github.com/free-audio/clap-wrapper/pull/294) with just the relevant commit (sorry!)

### CODE REVIEW

**Comment by MeijisIrlnd** [comment]
There's actually a much cleaner way to do the lifetime stuff I think - trying it now

**Comment by baconpaul** [comment]
I know from discord you are still thinking about shutdown path. I’m fine to merge this and it’s great but will hold until tomorrow to confirm - let me know if it’s ready

**Comment by MeijisIrlnd** [comment]
From what I can gather, the NSWindow will always clean itself up on close - so I *think* we can totally skip the cleanup in `applicationWillTerminate` - let me give this a try in a couple of hours, I'll see if anything alarming happens, and if not I'll do another push!

**Comment by MeijisIrlnd** [comment]
I mentioned in the Discord as well, but seems fine removing the `[window release]` stuff, and it's not crashing etc - I'm happy to sign off on this one unless there's anything you'd like me to change!

**Comment by baconpaul** [comment]
Fantastic! Merged!

**Pull request merged**
